[package]
name = "vcore"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }

nix = "0.26.2"
winapi = { version = "0.3.9", features = ["timeapi", "memoryapi", "processthreadsapi", "handleapi", "errhandlingapi"] }
